# Generated by Django 6.0.7 on 2026-07-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avtomobil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('yil', models.IntegerField()),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rangi', models.CharField(max_length=30)),
                ('dvigatel_hajmi', models.FloatField()),
                ('yurgan_masofasi', models.IntegerField()),
                ('yoqilgi_turi', models.CharField(max_length=20)),
                ('uzatmalar_qutisi', models.CharField(max_length=20)),
                ('yangi', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
            ],
        ),
    ]
